### ISSUE TITLE
Operator precendence bugs

### ISSUE THREAD

**Issue by andreas-gruenbacher** [zigorou/perl-json-pointer#8]
I'm getting operator precedence warnings in sub _is_iv_or_nv and sub _is_pv. Both functions contain the same line of code:
```perl
    return ($flags & ( B::SVp_IOK | B::SVp_NOK )) and !($flags & B::SVp_POK);
```
The problem here is that the "and" operator binds too weakly; the "&&" operator should be used instead. Obviously this has never worked before though, so I'm not sure if fixing this causes other problems.

**Comment by zigorou** [comment]
@andreas-gruenbacher 

I'll fix it in next release. Thank you.
